name: Java GitHub CI

run-name: Running default CI-checks for code pushed by ${{ github.actor }}

permissions: write-all

on:
  push:

jobs:
  build:
    name: Build application
    uses: ./.github/workflows/run_build_job.yml
    secrets: inherit
