name: Build application

on:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup build
        uses: gradle/gradle-build-action@v2

      - name: Execute gradle assemble
        run: ./gradlew :spring-boot-magic:bootJar
